<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Neillans.TemplateKit.Auth" />
    <PackageReference Include="Neillans.TemplateKit.Data" />
    <PackageReference Include="Exceptionless.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <RazorGenerate Remove="Theming/MaterioOverrides/import-backups/**/*.cshtml" />
    <Content Remove="Theming/MaterioOverrides/import-backups/**/*.cshtml" />
    <None Include="Theming/MaterioOverrides/import-backups/**/*.cshtml" />
  </ItemGroup>

</Project>
