// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitchTools.Web.Data;

#nullable disable

namespace TwitchTools.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824181003_AddKnownBots")]
    partial class AddKnownBots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwitchTools.Web.Domain.DiscordGuildSync", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId", "GuildId")
                        .IsUnique();

                    b.ToTable("DiscordGuildSyncs");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.EventSubDebugMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BroadcasterUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedUtc");

                    b.HasIndex("StreamerId");

                    b.ToTable("EventSubDebugMessages");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.KnownBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("KnownBots");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.LiveNotificationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlueSkyPostUri")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId", "RecordedUtc");

                    b.ToTable("LiveNotificationEvents");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.OverlaySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LastFollowerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastFollowerUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSubscriberName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastSubscriberUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("OverlaySnapshots");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.Streamer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlueSkyAppPassword")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BlueSkyIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("BlueSkyPostOnStreamStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("BlueSkyPostOnStreamStop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("BlueSkyStreamStartedTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlueSkyStreamStoppedTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomOverlayCss")
                        .HasColumnType("text");

                    b.Property<string>("CustomOverlayDataJson")
                        .HasColumnType("text");

                    b.Property<string>("CustomOverlayFieldsJson")
                        .HasColumnType("text");

                    b.Property<string>("CustomOverlayHtml")
                        .HasColumnType("text");

                    b.Property<string>("CustomOverlayJs")
                        .HasColumnType("text");

                    b.Property<string>("CustomOverlayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CustomOverlayToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CustomOverlayUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FollowerOverlayToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OverlayToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SubscriberOverlayToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TwitchBotAccessToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TwitchBotRefreshToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TwitchBotUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TwitchClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TwitchStreamerAccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TwitchStreamerRefreshToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CustomOverlayToken")
                        .IsUnique();

                    b.HasIndex("FollowerOverlayToken")
                        .IsUnique();

                    b.HasIndex("OverlayToken")
                        .IsUnique();

                    b.HasIndex("OwnerSubject")
                        .IsUnique();

                    b.HasIndex("SubscriberOverlayToken")
                        .IsUnique();

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("Streamers");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.SubscriberNotificationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsGift")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TwitchUserLogin")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TwitchUserName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId", "RecordedUtc");

                    b.ToTable("SubscriberNotificationEvents");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.TimedChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("LastSentUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId", "Enabled");

                    b.ToTable("TimedChatMessages");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.ViewerDurationSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalSecondsWatched")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchViewerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId", "TwitchViewerId", "CapturedUtc");

                    b.ToTable("ViewerDurationSamples");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.DiscordGuildSync", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.EventSubDebugMessage", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.LiveNotificationEvent", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany("LiveNotificationEvents")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.OverlaySnapshot", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithOne("OverlaySnapshot")
                        .HasForeignKey("TwitchTools.Web.Domain.OverlaySnapshot", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.SubscriberNotificationEvent", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany("SubscriberNotificationEvents")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.TimedChatMessage", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany("TimedChatMessages")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.ViewerDurationSample", b =>
                {
                    b.HasOne("TwitchTools.Web.Domain.Streamer", "Streamer")
                        .WithMany("ViewerDurationSamples")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchTools.Web.Domain.Streamer", b =>
                {
                    b.Navigation("LiveNotificationEvents");

                    b.Navigation("OverlaySnapshot");

                    b.Navigation("SubscriberNotificationEvents");

                    b.Navigation("TimedChatMessages");

                    b.Navigation("ViewerDurationSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
